services:
  veladns:
    image: ghcr.io/hyird/veladns:latest
    container_name: veladns
    restart: unless-stopped
    environment:
      AUTO_FORWARD: 172.16.0.101
      LOG_LEVEL: warn
    volumes:
      - ./data:/data
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 5304:5304/udp
      - 5304:5304/tcp
      - 127.0.0.1:5308:5308/tcp
